version: '3.8'
services:

  archive:
    image: archive-app:latest
    container_name: 'archive-app'
    depends_on:
      - mongo
      - minio
    ports:
      - 8081:8081

  mongo:
    image: mongo
    container_name: 'mongo'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "C:/DbStorage/mongo:/data"

  minio:
    image: minio/minio:latest
    container_name: 'minio'
    restart: always
    ports:
      - "9000:9000"
      - "9099:9099"
    volumes:
      - "C:/DbStorage/minio:/data"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address ":9099" --console-address ":9000" /data