version: '3.8'
services:

  archive:
    image: starskvim/starskvim-archive-app:latest
    container_name: 'archive-app'
    restart: always
    depends_on:
      - mongo
      - minio
    ports:
      - 8081:8081
    volumes:
      - "/mnt/hdd8-1/Archive/Figure:/Pigure"
      - "/mnt/hdd8-1/Archive/Pack:/Pack"
      - "/mnt/hdd8-1/Archive/Other:/Other"

  front:
    image: starskvim/starskvim-archive-front:latest
    container_name: 'archive-front'
    restart: always
    depends_on:
      - archive
    ports:
      - 3000:3000

  mongo:
    image: mongo
    container_name: 'mongo'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/mnt/ssd500/DbStorage/Mongo:/data/db"

  minio:
    image: minio/minio:latest
    container_name: 'minio'
    restart: always
    ports:
      - "9000:9000"
      - "9099:9099"
    volumes:
      - "/mnt/ssd500/DbStorage/Minio:/data"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address ":9099" --console-address ":9000" /data