server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

minio:
  endpoint: http:/minio:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1:
  address2:
  address3: