server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

minio:
  endpoint: http:/minio:9099
  external: http://192.168.0.114:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1: /Pigure
  address2: /Pack
  address3: /Other

archive-properties:
  version: "0.0.2-SNAPSHOT"
  saveBatch: 100
  coroutineBatch: 100
  tempFolderPath: "?"

springdoc:
  show-actuator: false
  api-docs.enabled: false
  swagger-ui.enabled: false

google:
  gemini:
    job: true
    cron: "*/60 * * * * *"
    batch-size: 10
    base-url: https://generativelanguage.googleapis.com/v1beta/models
    model: gemini-2.0-flash
    processor-name: gemini-2.0-flash
    models:
      - model: gemini-2.0-flash-lite
        limit: 200
      - model: gemini-2.0-flash
        limit: 200
      - model: gemini-1.5-flash-latest
        limit: 200
    exclude-tags: ["3d render", "3d model", "model", "figurine", "render", "stl"]

job:
  first-create-meta:
    cron: "*/60 * * * * *"
  retry-create-meta:
    cron: "*/60 * * * * *"

openrouter:
  base-url: "https://omnirouter.chamkin.ru/v1" # "https://openrouter.ai/api/v1"
  #    model: "openai/gpt-4.1-nano"
  model: "antigravity/gemini-3.7-flash-high" # "google/gemini-3-flash-preview"
  batch-size: 10
  image-per-print-model: 3
  exclude-tags: [ "3d render", "model", "figurine", "zbrush" ]

local-context:
  job: false