server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

minio:
  endpoint: http:/minio:9099
  external: http://192.168.0.114:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1: /figure
  address2: /pack
  address3: /other

archive-properties:
  saveBatch: 100
  coroutineBatch: 100

springdoc:
  show-actuator: false
  api-docs.enabled: false
  swagger-ui.enabled: false
