server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

minio:
  endpoint: http://127.0.0.1:9099
  external: http://127.0.0.1:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1: F:\[Patreon]\[test]
  address2: F:\[Patreon]\[test]
  address3: F:\[Patreon]\[test]

archive-properties:
  version: "0.0.2-SNAPSHOT"
  saveBatch: 100
  coroutineBatch: 100
  tempFolderPath: F:\[Patreon]\[archive temp]

springdoc:
  show-actuator: true
  api-docs.enabled: true
  swagger-ui.enabled: true