server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

minio:
  endpoint: http:/minio:9099
  external: http://192.168.0.114:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1: /Pigure
  address2: /Pack
  address3: /Other

archive-properties:
  version: "0.0.2-SNAPSHOT"
  saveBatch: 100
  coroutineBatch: 100
  tempFolderPath: "?"

springdoc:
  show-actuator: false
  api-docs.enabled: false
  swagger-ui.enabled: false

google:
  gemini:
    job: false
    cron: "*/60 * * * * *"
    batch-size: 10
    base-url: https://generativelanguage.googleapis.com/v1beta/models
    model: gemini-2.0-flash
    processor-name: gemini-2.0-flash-v1
    api-key: ""
    exclude-tags: [ "3d render", "model", "figurine" ]

openrouter:


local-context:
  job: false