server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: archive
      port: 27017
      database: PrintModelsArchive
  webflux:
    base-path: /archive

scan:
  addressSer: G:\[Model]\save
  address1: D:\[Patreon]\[Figure]
  address2: D:\[Patreon]\[Other]
  address3: D:\[Patreon]\[Pack]