server:
  port: 8081

spring:
  data:
    mongodb:
      port: 27017
      database: archive
  webflux:
    base-path: /archive
  thymeleaf:
    prefix: file:src/main/resources/templates/

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

minio:
  endpoint: http://127.0.0.1:9099
  secretKey: minioadmin
  accessKey: minioadmin

scan:
  address1: F:\[Patreon]\[Unsorted]
  address2: F:\[Patreon]\[test]
  address3: F:\[Patreon]\[test]